spring:
  datasource:
    url: jdbc:mysql://docker-mysql:3306/customerdb
    username: root
    password: root

  jpa:
    show-sql: true
    
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  
  redis:
    cluster:
      nodes:
      - redis-1:6379,redis-2:6379,redis-3:6379,redis-4:6379,redis-5:6379,redis-6:6379
      max-redirects: 3
     
    lettuce:
      pool:
        max-idle: 10
        max-wait: 500
    database: 0
    
          
  cache: 
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 100000
      use-key-prefix: true

management:
  endpoints:
    web: 
      exposure:
        include:
        - "*"


    
server:
  port: 8080
  
logging:
  file:
    name: customer.log
    path: ../logs
    
